const userStore = [
  {
    id: 1,
    first_name: "first_name1",
    last_name: "last_name1",
    name:"first user",
    user_name:"user1",
    profile_picture: "picture_path1",
    gender: "male",
    email: "example1@gmail.com",
    password: "password",
    following_ids: [],
    tag_ids: [],
    like_ids: [1],
    dislike_ids: [1],
    report_ids: [1],
    comment_id: 1,
  },
  {
    id: 2,
    first_name: "first_name2",
    last_name: "last_name2",
    name:"second user",
    user_name:"user2",
    profile_picture: "picture_path2",
    gender: "female",
    email: "example2@gmail.com",
    password: "password",
    following_ids: [],
    tag_ids: [],
    like_ids: [2],
    dislike_ids: [2],
    report_ids: [2],
    comment_id: 2,
  },
  {
    id: 3,
    first_name: "first_name3",
    last_name: "last_name3",
    name:"third user",
    user_name:"user3",
    profile_picture: "picture_path3",
    gender: "male",
    email: "example3@gmail.com",
    password: "password",
    following_ids: [],
    tag_ids: [],
    like_ids: [3],
    dislike_ids: [3],
    report_ids: [3],
    comment_id: 3,
  },
];

export const defaultUser = {
  id: null,
  first_name: null,
  last_name: null,
  profile_picture: null,
  gender: null,
  email: null,
  password: null,
  following_ids: [],
  tag_ids: [],
  like_ids: [],
  dislike_ids: [],
  report_ids: [],
  comment_id: [],
};
export default userStore;
