const userStore = [
  {
    id: 1,
    first_name: "first_name1",
    last_name: "last_name1",
    profile_picture: "picture_path1",
    gender: "male",
    email: "example1@gmail.com",
    password: "password",
    following_ids: [2, 3],
    tag_ids: [1, 2],
    like_ids: [1],
    dislike_ids: [1],
    report_ids: [1],
    comment_id: 1,
  },
  {
    id: 2,
    first_name: "first_name2",
    last_name: "last_name2",
    profile_picture: "picture_path2",
    gender: "female",
    email: "example2@gmail.com",
    password: "password2",
    following_ids: [1, 3],
    tag_ids: [1, 2],
    like_ids: [2],
    dislike_ids: [2],
    report_ids: [2],
    comment_id: 2,
  },
  {
    id: 3,
    first_name: "first_name3",
    last_name: "last_name3",
    profile_picture: "picture_path3",
    gender: "male",
    email: "example3@gmail.com",
    password: "password",
    following_ids: [2, 1],
    tag_ids: [1, 2, 3],
    like_ids: [3],
    dislike_ids: [3],
    report_ids: [3],
    comment_id: 3,
  },
];

export default userStore;
